
env:
 global:
   - PROJECT_NAME=dust
   - CHANNEL=stable

language: rust
rust:
  - stable
matrix:
    - os: osx
      env: TARGET=i686-apple-darwin
    - os: linux
      env: TARGET=i686-unknown-linux-gnu
    - os: osx
      env: TARGET=x86_64-apple-darwin
    - os: linux
      env: TARGET=x86_64-unknown-linux-gnu
cache: cargo

